### ISSUE TITLE
Listening on port 9000...

### ISSUE THREAD

**Issue by dave7802** [gwomacks/php-debug#140] opened 2016-03-08 10:38 UTC
My Config.cson shows: 

"php-debug":
  {
    ServerPort: 8080
  }

Not 9000
Does this mean the Package is failing to pickup a None Default port?
Or is it not reading my settings?
Or can i simply not use a different port of than 9000

Confused, I use a PHPed, debugger works fine on port 8080
and all application have worked for years using this same setup.

Atom just does not want to play ball

**Comment by cchamplin** [comment] 2016-05-05 15:31
I am unable to reproduce this, are you still experiencing this issue?

**Comment by dave7802** [comment] 2016-05-05 15:35
i actually give up in the end. 
I completely forgot i was trying to use Debugger in Atom. 
Let me update everything and revisit this.

**Comment by QwertyZW** [comment] 2016-10-09 06:28
I have the same issue, I know it's listening on the port because I checked to see if it is open.

**Comment by cchamplin** [comment] 2016-10-14 04:22
Can you let me know what OS your're on? My guesses are that this is possibly a windows permission/firewall rule and Atom is not being allowed to bind to that port. A quick way to check would be to try running atom as an Administrator.

**Comment by QwertyZW** [comment] 2016-10-14 04:31
Nevermind I actually figured it out...My "php-debug" config wasn't tabbed under "*", it was just floating there. My guess is that's why it didn't get loaded

**Comment by QwertyZW** [comment] 2016-10-14 04:36
If port binding fails the package throws an exception, and it does that at 2 or 3 places. If you read OP's post carefully you'll realize that it's a matter of selecting the port to be listened on as opposed to receiving connections. The whole purpose of this test was to check if my config was loaded properly. I eventually figured out that my PathMaps also weren't loaded which prevented the package from functioning at all. This can be solved with a simple test. 

I've written code that fixes this but the lack of activity on this repo discouraged me from contributing.

I also emailed you about this. (using the email visible on your profile)

**Comment by cchamplin** [comment] 2016-10-14 05:01
Please feel free to submit pull requests.

This project is definitely not dead or unmaintained at this point. The unfortunate reality is that this and several other projects I maintain are done in my free time apart from my full time job, which occasionally results in larges gaps in me being able to contribute and answer questions. So pull requests are definitely appreciated, even if they can't be reviewed asap.

I'm going to close this issue for now, and I look forward to a pull request from you :)

**Closed by cchamplin** 2016-10-14 05:01 UTC
