### ISSUE TITLE
unicode charactors are not correctly showed!

### ISSUE THREAD

**Issue by wuceyang** [gwomacks/php-debug#160] opened 2016-04-29 06:47 UTC
unicode charactors are unreadable!

**Comment by cchamplin** [comment] 2016-05-05 17:39
Duplicate of #157.

**Closed by cchamplin** 2016-05-05 17:39 UTC

**Comment by nahuelhds** [comment] 2016-10-20 14:19
@cchamplin still without possibilities of fixing this? I work with some spanish special chars (accents specially). It'd be nice to properly see them in the console!
