### ISSUE TITLE
atom-ide integration

### ISSUE THREAD

**Issue by ttadegraaff** [gwomacks/php-debug#302] opened 2018-06-05 10:10 UTC
The atom-ide package (https://ide.atom.io/) in combination with the ide-php provides some nice functionality for php development, including an environment for debugging functionality. Are there any plans to add integration for php-debug with atom-ide so php-debug can be selected as a debugger when using atom-ide?

**Comment by cchamplin** [comment] 2018-09-09 22:48
Duplicate of #271. This is something that I would be willing to work towards, but it's unlikely to occur in 2018.

**Closed by cchamplin** 2018-09-09 22:48 UTC
Labels: duplicate
