### ISSUE TITLE
Uncaught Error: listen EADDRINUSE :::9001

### ISSUE THREAD

**Issue by Aclopes** [gwomacks/php-debug#63] opened 2015-07-13 21:29 UTC
1. Toggle the Breakpoint
2. Click in Menu > Pakages> PHP-Debug > Toggle Debuging.

Nothing more.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.1.2

### Stack Trace

Uncaught Error: listen EADDRINUSE :::9001

```
At events.js:141

Error: listen EADDRINUSE :::9001
    at Object.exports._errnoException (util.js:734:11)
    at exports._exceptionWithHostPort (util.js:757:20)
    at Server._listen2 (net.js:1173:14)
    at listen (net.js:1203:10)
    at Server.listen (net.js:1290:5)
    at Dbgp.module.exports.Dbgp.listen (/Users/alex/.atom/packages/php-debug/lib/engines/dbgp/dbgp.coffee:47:17)
    at Object.module.exports.PhpDebug.toggleDebugging (/Users/alex/.atom/packages/php-debug/lib/php-debug.coffee:343:28)
    at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleDebugging (/Users/alex/.atom/packages/php-debug/lib/php-debug.coffee:149:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
```

### Commands

```
     -8:29.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -8:26 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:13.6.0 php-debug:clearAllBreakpoints (atom-text-editor.editor.is-focused)
     -3:54.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -3:54.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -3:44.5.0 php-debug:clearAllBreakpoints (atom-text-editor.editor.is-focused)
     -3:30.3.0 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
     -0:36.3.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
  2x -0:09.2.0 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "linter-js-standard"
    ]
  },
  "php-debug": {
    "ServerPort": 9001,
    "PhpException": {}
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
aligner-php, v1.0.0
linter, v1.2.3
linter-php, v0.0.15
php-debug, v0.1.2

# Dev
No dev packages
```

**Comment by marza91** [comment] 2015-08-23 20:03
Hey, I also had this problem and it seems the cause was that another program (php-fpm) was already listening on the same port (9000 in my case). I fixed it by making php-fpm a socket instead ( listen = /run/php-fpm/php-fpm.sock in the conf), but it could also probably be fixed by changing the port for php-debug and xdebug (they have to be the same).
Anyway, I guess the issue here is that an obscure uncaught exception is thrown, but it should rather warn/alert the user saying that you're trying to listen on a port that's been taken?
I'm guessing #67 is the same as this one.

**Closed** 2016-01-19 23:21 UTC
