### ISSUE TITLE
Right clicking on a "Find in Project" input causes a TypeError

### ISSUE THREAD

**Issue by Aetheus** [gwomacks/php-debug#182] opened 2016-09-13 08:59 UTC
Encountering this error when trying to right-click an input in Find in Project - "Uncaught TypeError: editor.getSelectedText is not a function"

![GIF movie](http://imgur.com/w24Gt1K.gif)

## Repro Steps

1. Open the "Find in Project" menu (Ctrl-Shift-F on Windows)
2. Execute a search with any search query
3. Navigate to the search result tab.
4. Attempt to right click on your search query

**Expected:** The normal context menu appears, allowing you to do things like Copy, Cut, etc
**Actual:** Nothing happens, and the following line is logged to the debug console:

      php-debug.coffee:196 Uncaught TypeError: editor.getSelectedText is not a function

## Command History

```
     -0:01.6 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (atom-text-editor.editor.is-focused)
```

## Versions

* **Atom:**       1.10.2
* **Atom-Shell:** 
* **OS:**         Microsoft Windows 7 Professional 
* **Misc**
    * apm  1.12.5
    * npm  3.10.5
    * node 4.4.5
    * python 
    * git 2.8.0.windows.1
    * visual studio 2015

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by cchamplin** [comment] 2016-10-14 04:18
Duplicate of #170

**Closed by cchamplin** 2016-10-14 04:18 UTC
