### ISSUE TITLE
Uncaught TypeError: _ref1.destroy is not a function

### ISSUE THREAD

**Issue by betterphp** [gwomacks/php-debug#152] opened 2016-04-08 11:21 UTC
[Enter steps to reproduce below:]

1. Add a breakpoint and start debugging
2. While debugger is running try to remove breakpoint / press CTRL + ALT + D

After this clicking stop then trying to CTRL + ALT + D will produce the following and leave the debugger pane open

**Atom Version**: 1.6.2
**System**: Ubuntu 15.10
**Thrown From**: [php-debug](https://github.com/gwomacks/php-debug) package, v0.2.2

### Stack Trace

Uncaught TypeError: _ref1.destroy is not a function

```
At /home/jacek/.atom/packages/php-debug/lib/php-debug.coffee:335

TypeError: _ref1.destroy is not a function
    at Object.module.exports.PhpDebug.toggleDebugging (/home/jacek/.atom/packages/php-debug/lib/php-debug.coffee:335:22)
    at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleDebugging (/home/jacek/.atom/packages/php-debug/lib/php-debug.coffee:114:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:260:29)
    at /opt/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/opt/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:49.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:49.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:43.9.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:43.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -2:39 core:backspace (atom-text-editor.editor.is-focused)
     -2:29.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:29.7.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:29.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:28.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:18.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:15.4.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
     -2:15.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:23.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:19.2.0 php-debug:toggleBreakpoint (atom-text-editor.editor.is-focused)
  3x -0:16.8.0 php-debug:toggleDebugging (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "php-debug": {
    "PathMaps": [
      "/var/www/jmk/payroll-hub;/media/shares/work/dev-web/payroll-hub"
    ]
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
emmet, v2.4.3
highlight-line, v0.11.1
highlight-selected, v0.11.2
line-ending-converter, v1.3.2
linter, v1.11.4
linter-php, v1.2.0
markdown-scroll-sync, v2.1.2
php-debug, v0.2.2

# Dev
No dev packages
```

**Comment by cchamplin** [comment] 2016-05-05 16:00
I am unable to reproduce this, closing for now. We'll see if it pops back up.

**Closed by cchamplin** 2016-05-05 16:00 UTC

**Comment by robbieaverill** [comment] 2016-05-12 21:56
This occurred for me when simply toggling debugging via the UI menu.

**Comment by Cristo-Conklin** [comment] 2016-06-05 10:29
I'm having the same issue trying to enable/disable debugger on right click from atom, while it's in listening state

```
TypeError: _ref1.destroy is not a function
    at Object.module.exports.PhpDebug.toggleDebugging (file:///C:/Users/Cristo/.atom/packages/php-debug/lib/php-debug.coffee:341:22)
    at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleDebugging (file:///C:/Users/Cristo/.atom/packages/php-debug/lib/php-debug.coffee:119:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Cristo\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Cristo\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Cristo\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Cristo\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\atom-environment.js:1106:28)
    at EventEmitter.outerCallback (C:\Users\Cristo\AppData\Local\atom\app-1.8.0-beta4\resources\app.asar\src\application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

**Comment by LoghamLogan** [comment] 2016-08-04 15:36
+1 here.
```
TypeError: _ref1.destroy is not a function
    at Object.module.exports.PhpDebug.toggleDebugging (file:///C:/Users/username/.atom/packages/php-debug/lib/php-debug.coffee:341:22)
    at atom-workspace.subscriptions.add.atom.commands.add.php-debug:toggleDebugging (file:///C:/Users/user.name/.atom/packages/php-debug/lib/php-debug.coffee:119:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user.name\AppData\Local\atom\app-1.9.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\user.name\AppData\Local\atom\app-1.9.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\user.name\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\user.name\AppData\Local\atom\app-1.9.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\user.name\AppData\Local\atom\app-1.9.2\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\user.name\AppData\Local\atom\app-1.9.2\resources\app.asar\src\window-event-handler.js:3:61)
```

**Comment by LoghamLogan** [comment] 2016-08-04 15:42
I had another app listening for xdebug at the same time;
Stopping the program listening for xdebug then restarting Atom fixed the issue for me.

**Comment by bart1970** [comment] 2016-10-25 07:45
Issue occurred when a phtml source file changed and the breakpoint ended-up after the eof. The breakpoint keeps coming back, even when removed. And cannot stop debugging.
