### ISSUE TITLE
Suggestion: Add pop up that shows variable value

### ISSUE THREAD

**Issue by sbrl** [gwomacks/php-debug#195] opened 2016-11-16 16:44 UTC
In visual studio, when I'm debugging C#, I can mouse over a variable and a pop-up box that displays the variable's value. it would be seriously cool if this plugin would do that too.

**Comment by kenorb** [comment] 2017-07-01 17:53
Duplicate of: #153

**Closed** 2017-07-05 20:32 UTC
Labels: enhancement, no work planned

**Comment by sbrl** [comment] 2017-07-05 20:35
I'm closing this as a duplicate then, @kenorb. I should have spotted that when initially opening the issue! What I don't get though is the `no work planned` label rather than closing it as a duplicate.
