### ISSUE TITLE
Multiple tabs keep opening when current breakpoint wasn't explicitly continued

### ISSUE THREAD

**Issue by tominventisbe** [gwomacks/php-debug#289] opened 2018-05-08 13:19 UTC
I assume this is due to the nature of the "allow multiple sessions" setting, but even disabling it keeps spawning an additional two tabs (the console and the debug UI) per new request that comes in.

I'm not sure if any of these are possible, but the following would perhaps be interesting:
* Ignore any additional requests and log a message to the console that a second request could not be attached to because another one is already being handled (in the same window)
* Exit the current handling if the request is aborted, though this may be annoying for the developer debugging

**Comment by cchamplin** [comment] 2018-05-21 15:53
Duplicate of #291 

This should be fixed in the next release (sometime this week). There is a flag that's sent to xdebug but to disable multiple connections but it looks like xdebug is ignoring this in certain situations.

**Comment by cchamplin** [comment] 2018-05-26 17:31
Should be Fixed in v0.3.5. If not please reopen

**Closed by cchamplin** 2018-05-26 17:31 UTC
Labels: bug, confirmed, duplicate
